services:
  drawsteel:
    image: drawsteel
    build:
      context: .
      dockerfile: src/Web/Dockerfile
    container_name: web-app
    ports:
      - 3000:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development