services:
  draw-steel:
    image: thooper91/draw-steel:dev
    build:
      context: .
      dockerfile: src/Web/Dockerfile
    container_name: web
    ports:
      - 3000:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development