@baseUrl = http://localhost:5000

GET {{baseUrl}}/api/healthcheck
###
GET {{baseUrl}}/api/ping?code=test
###
POST {{baseUrl}}/api/characters?code=test
Content-Type: application/json

{
    "name": "Sam"
}