@characterId=

POST /characters
Content-Type: application/json
Accept: application/json

{
  "name": "Gandalf"
}

###

GET /characters/{{characterId}}

###

PUT /characters/{{characterId}}
Content-Type: application/json
Accept: application/json

{
  "id": {
    "value": "{{characterId}}"
  },
  "name": "Gandalf the White"
}

###

DELETE /characters/{{characterId}}